# Generated by Django 3.1.3 on 2021-01-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_name', models.CharField(max_length=50)),
                ('cand_mobile', models.CharField(max_length=10)),
                ('cand_email', models.EmailField(max_length=254)),
                ('mdf_date', models.CharField(max_length=30)),
                ('act_date', models.CharField(max_length=30)),
                ('excuse', models.BooleanField(default=False)),
            ],
        ),
    ]
