# Generated by Django 3.1.3 on 2021-01-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
