# Generated by Django 3.1.3 on 2021-01-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210105_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('cand_name', 'mdf_date', 'act_date')},
        ),
    ]
