# Generated by Django 3.1.3 on 2021-01-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210105_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set(),
        ),
    ]
