# Generated by Django 3.1.3 on 2021-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210105_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_mobile', models.CharField(max_length=10)),
                ('send_date', models.CharField(max_length=30)),
                ('send_time', models.CharField(max_length=2)),
            ],
        ),
    ]
